class Solution {
        public String shortestBeautifulSubstring(String s, int k) {
                int n = s.length();
                        String result = "";
                                
                                        for (int i = 0; i < n; i++) {
                                                    int ones = 0;
                                                                for (int j = i; j < n; j++) {
                                                                                if (s.charAt(j) == '1') {
                                                                                                    ones++;
                                                                                                                    }
                                                                                                                                    
                                                                                                                                                    if (ones == k) {
                                                                                                                                                                        String candidate = s.substring(i, j + 1);
                                                                                                                                                                                            
                                                                                                                                                                                                                if (result.isEmpty() 
                                                                                                                                                                                                                                        || candidate.length() < result.length() 
                                                                                                                                                                                                                                                                || (candidate.length() == result.length() && candidate.compareTo(result) < 0)) {
                                                                                                                                                                                                                                                                                        result = candidate;
                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                    break; // no need to extend further right from this i; more 1's only makes it longer
                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                        return result;
                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                            }
